name: pushed_updates
run-name: ${{ github.actor }} is updating the docs, after changes were made
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Doesn't actually run the command.
        default: false

jobs:
  execute-command:
    if: ${{ github.triggering_actor == github.repository_owner }}
    name: Use tailscale to connect and execute command.
    runs-on: ubuntu-24.04
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: getting boolean status
        run: echo ${{inputs.dry-run}}
        shell: bash
      - name: executing remote ssh commands using password
        if: ${{ inputs.dry-run == false }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_TS }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
